name: Profiler

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      game-count:
        description: "Number of randomized games to be play"
        required: false
        default: 45
      run-name:
        description: "Name of the run"
        required: false
        default: " "

run-name: ${{ github.event.inputs.run-name }}

env:
  ENVIRONMENT: "GITHUB"

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: Profiling the code
      run: |
        echo "## Profiler Stats :hourglass: ##" >> $GITHUB_STEP_SUMMARY
        python profiling.py
  